---
resources:
- name: resource-every-1m
  type: time
  source: {interval: 1m}

jobs:
- name: job-ring
  plan:
  - get: resource-every-1m
    trigger: true
  - task: task-ring
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: 10.244.0.103:443/busybox
          insecure_registries: [ "10.244.0.103:443" ]
          tag: latest
      run:
        path: sh
        args:
          - -exc
          - |
            date
            echo "I love Concourse!"