---
resources:
- name: resource-git
  type: git
  source:
    uri: https://github.com/brightzheng100/concourse-demo.git

jobs:
- name: job-inputs-outputs
  public: true
  plan:
  - get: resource-git
  - task: task-create-some-files
    file: resource-git/tasks/task_create_some_files.yml
  - task: task-show-some-files
    file: resource-git/tasks/task_show_files.yml
