---

# this is a demo for why this is NOT going to work

- name: resource-every-1m
  type: time
  source: {interval: 1m}

jobs:
- name: job-ring
  plan:
  - get: resource-every-1m
    trigger: true
  - task: task-ring
    file: tasks/task_ring.yml