---
platform: linux

image_resource:
  type: docker-image
  source: {repository: busybox}

run:
  path: sh
  args:
  - -exc
  - |
    sleep 100
    echo "my_secret is ${my_secret}"

params:
  my_secret: